name: dyphic
description: Daily physical condition recording App.

# pub.devには公開しないのでnone
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # design
  provider: ^5.0.0
  path_provider: ^2.0.1
  path: ^1.8.0

  # ui
  table_calendar: ^3.0.0-nullsafety.1
  image_picker: ^0.7.2+1
  expansion_tile_card: ^2.0.0

  # network
  http: ^0.13.0
  cached_network_image: ^3.0.0-nullsafety

  # storage
  sqflite: ^2.0.0+2
  shared_preferences: ^2.0.4

  # other
  package_info: ^2.0.0
  logger: ^1.0.0-nullsafety.0
  intl: ^0.17.0

  # Firebase
  google_sign_in: ^5.0.0
  firebase_core: ^1.0.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.1
  firebase_storage: ^8.0.0
  firebase_crashlytics: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - res/images/

