name: dyphic
description: Daily physical condition recording App.

publish_to: 'none'

version: 3.0.0+14

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # design
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # UI
  table_calendar: ^3.1.2
  expansion_tile_card: ^3.0.0

  # local storage
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Firebase
  google_sign_in: ^6.2.1
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_crashlytics: ^4.3.6

  # other
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  logger: ^2.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  riverpod_generator: ^2.4.0
  isar_generator: ^3.1.0+1
  
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/launcher/
